---
- name: Install HAProxy
  hosts: all
  become: true
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Copy HAProxy configuration file
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify:
        - restart haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted

