---
- name: Deploy Flask application
  hosts: all
  become: yes

  tasks:

    - name: Install Python and Flask
      ansible.builtin.pip:
        name:
          - flask

    - name: Copy Flask application script
      ansible.builtin.copy:
        src: application2.py
        dest: /home/application2.py
        mode: '0755'

    - name: Start Flask application
      ansible.builtin.shell:
        cmd: "python /home/application2.py &"

    - name: Start Flask application2
      ansible.builtin.command: python3 /home/application2.py &
