---
- name: Deploy Flask application and install HAProxy
  hosts: dev
  become: true
  tasks:
    - name: Create SSH directory for root
      become_user: root
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'

    - name: Copy SSH key for root
      become_user: root
      copy:
        src: /home/student/.ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
        mode: '0600'

    - name: Install Requirmnets
      pip:
        name:
          - net-tools

    - name: Install Python and Flask
      pip:
        name:
          - flask

    - name: Copy Flask application script
      copy:
        src: application2.py
        dest: /home/application2.py
        mode: '0755'

    - name: Start Flask application
      shell:
        cmd: "python /home/application2.py &"

    - name: Start Flask application2
      command: python3 /home/application2.py &

    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Copy HAProxy configuration file
      copy:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
      notify:
        - restart haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted

